# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    undertow:
            accesslog:
              dir:  # Undertow access log directory.
              enabled: false  # Enable access log.
              pattern: common   # Format pattern for access logs.
              prefix: access_log  # Log file name prefix.
              rotate: true  # Enable access log rotation.
              suffix: log   # Log file name suffix.
            buffer-size:  # Size of each buffer in bytes.
            direct-buffers:   # Allocate buffers outside the Java heap.
            io-threads:   # Number of I/O threads to create for the worker.
            max-http-post-size: 0  # Maximum size in bytes of the HTTP post content.
            worker-threads:   # Number of worker threads.
# mysql
spring:
    # 环境 dev|test|pro|loc
    profiles:
        active: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss

    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    # 指定静态资源的路径
    resources:
        static-locations: classpath:/static/,classpath:/templates/
# Mybatis配置
mybatis:
    mapperLocations: classpath:mybatis/mapper/**/*.xml
    configLocation: classpath:mybatis.xml